spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hppproject?allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: joy
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: prod

server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password:
    key-store-type: PKCS12
